const frases_motivacionais = [
  "Menos é mais.",
  "A simplicidade é o último grau de sofisticação.",
  "Viva com menos e valorize mais.",
  "Desapegue do excesso e descubra a liberdade.",
  "A vida é sobre momentos, não posses.",
  "A verdadeira riqueza está nas coisas que o dinheiro não pode comprar.",
  "O minimalismo é a chave para uma vida de propósito.",
  "Deixe espaço para o que realmente importa.",
  "O simples não é sobre falta, mas sobre o essencial.",
  "Preencha sua vida com experiências, não coisas.",
  "A felicidade vem quando você aprecia o que tem.",
  "Busque o essencial e ignore o supérfluo.",
  "Menos bagunça, mais clareza.",
  "Reduza o ruído para ouvir o que é importante.",
  "A vida minimalista é um caminho para a paz interior.",
  "Concentre-se no que traz valor, não volume.",
  "Viver com menos é viver com mais liberdade.",
  "O excesso pode sufocar a alma.",
  "A simplicidade nos ensina a apreciar o presente.",
  "O minimalismo é um convite à consciência.",
  "Simplifique sua mente, simplifique sua vida.",
  "A verdadeira abundância é saber que já temos o suficiente.",
  "A arte de viver está em saber o que deixar de lado.",
  "Menos coisas, mais vida.",
  "Viva de forma simples, pense de forma clara.",
  "O segredo da felicidade é encontrar alegria nas pequenas coisas.",
  "As coisas mais simples muitas vezes são as mais belas.",
  "Quanto menos você precisa, mais livre você é.",
  "Menos posse, mais paz.",
  "Liberte-se do que não serve mais.",
  "O minimalismo é a beleza do espaço vazio.",
  "A vida é curta demais para ser complicada.",
  "O essencial é invisível aos olhos.",
  "Viver simples é viver leve.",
  "Menos distrações, mais significado.",
  "O minimalismo é uma jornada, não um destino.",
  "A simplicidade é o verdadeiro luxo.",
  "Gaste seu tempo com o que realmente importa.",
  "Seja feliz com menos.",
  "Possuir menos é igual a ser mais.",
  "A simplicidade revela a verdadeira essência da vida.",
  "Menos busca por mais, mais apreciação pelo agora.",
  "A vida fica melhor quando você a descomplica.",
  "Desapegar não é perder, é ganhar espaço.",
  "A beleza da vida está na simplicidade dos momentos.",
  "Mantenha apenas o que te faz feliz.",
  "A verdadeira riqueza é viver em paz com pouco.",
  "Desapegue do que pesa, abrace o que liberta.",
  "Menos ego, mais amor.",
  "Quem tem menos, valoriza mais.",
  "Viver simples é um ato de coragem.",
  "Simplificar é eliminar o desnecessário para que o necessário possa se manifestar.",
  "A clareza vem com a simplicidade.",
  "Quanto mais simples a vida, mais verdadeiro o propósito.",
  "Viva de forma consciente, viva de forma simples.",
  "Desfrute do silêncio e da quietude que o minimalismo proporciona.",
  "Liberdade é não precisar de muito.",
  "O excesso rouba a paz, o simples a devolve.",
  "Escolha qualidade ao invés de quantidade.",
  "A vida é mais leve quando não está sobrecarregada.",
  "A simplicidade é a alma da eficiência.",
  "O caminho para a felicidade é simples, mas nem sempre fácil.",
  "Viva no presente, não no excesso.",
  "Menos preocupação com o material, mais foco no espiritual.",
  "Quanto menos você tem, mais você aprecia.",
  "Viva devagar, viva simples.",
  "A simplicidade é a chave para a liberdade emocional.",
  "A paz interior é o maior luxo que você pode ter.",
  "Concentre-se no que você pode controlar, libere o que não pode.",
  "Simplificar é encontrar liberdade no essencial.",
  "Menos complicação, mais conexão.",
  "O minimalismo é uma prática de gratidão.",
  "Viver com menos é ter mais tempo para si mesmo.",
  "Simplicidade não é privação, é liberdade.",
  "Quanto menos coisas nos ocupam, mais espaço temos para o que importa.",
  "A verdadeira beleza da vida é revelada na simplicidade.",
  "Desacelere e aprecie o que está à sua frente.",
  "Menos tralha, mais alma.",
  "O segredo de uma vida feliz está em ser simples.",
  "Liberte-se da mentalidade de escassez.",
  "O simples é, muitas vezes, o mais profundo.",
  "Viver leve é viver sem excesso.",
  "Simplicidade traz clareza, clareza traz propósito.",
  "O minimalismo é um caminho para o autoconhecimento.",
  "Reduza o que te distrai, aumente o que te inspira.",
  "Quem precisa de menos, vive mais.",
  "A liberdade está em não precisar de nada além do essencial.",
  "O minimalismo é uma forma de amor próprio.",
  "O simples é suficiente.",
  "O desapego traz paz ao coração.",
  "Menos expectativas, mais gratidão.",
  "A vida fica mais rica quando você simplifica.",
  "Viver com menos é viver com mais intencionalidade.",
  "Menos objetos, mais experiências.",
  "A vida simples é uma vida plena.",
  "Viver com menos não significa viver com falta.",
  "Aprecie a beleza nas pequenas coisas.",
  "O essencial é o suficiente.",
  "Simplifique para viver melhor.",
  "Menos é tudo o que você realmente precisa.",
  "A verdadeira felicidade vem do interior, não do exterior."
];
export function GET() {
  let pos =  Math.floor(frases_motivacionais.length * Math.random());
  let f =
    frases_motivacionais[ pos  ];

  return Response.json({id:pos,  message: f });

}